apiVersion: v2
name: sscs-bulk-scan
home: https://github.com/hmcts/sscs-bulk-scan
version: 0.0.29
description: SSCS Bulk Scan
maintainers:
  - name: HMCTS SSCS Team
dependencies:
  - name: java
    version: 3.7.3
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
